### ISSUE TITLE
srv support

### ISSUE THREAD

**Issue by look416** [transferwise/pipelinewise-tap-mongodb#12]
Currently, it's not supporting the `SRV` URL from mongo Atlas. We will need to manually install `dnspython` package using pip. 

Recommend to include it under setup.py.

**Comment by Samira-El** [comment]
Hey, congrats on the first issue in this repo and thanks for reporting this! 

Is adding `dnspython` all that is needed to support `SRV` urls?

**Comment by look416** [comment]
Yes, just the package will do. For now, I'm changing the pipelinewise `install.sh` script to include that package for `tap-mongodb`.

**Comment by Samira-El** [comment]
Thanks for the initiative! however, adding packages for this tap should be in [pipelinewise-tap-mongodb's setup.py](https://github.com/transferwise/pipelinewise-tap-mongodb/blob/master/setup.py)

**Comment by look416** [comment]
Yeap, but since the pipelinewise is using the pypi packages to get the `tap-mongodb`, it will be easier for me to edit the `install.sh` while waiting the updates from your side. Once you have updated the packages, I will just revert the changes under `install.sh`.

**Comment by Samira-El** [comment]
Hey, can you try to use pipelinewise with tap-mongodb pulled from this branch https://github.com/transferwise/pipelinewise-tap-mongodb/tree/AP-836 and let me know if the replication works?

**Comment by look416** [comment]
Hi, yes, I have tried with the branch `AP-836`. It's working now. Thanks

**Comment by Samira-El** [comment]
Hey, I release the new version with SRV support https://pypi.org/project/pipelinewise-tap-mongodb/1.2.0/

>Hi, yes, I have tried with the branch AP-836. It's working now. Thanks
How about the FastSync in pipelinewise? does the full sync work too without any changes?
